### ISSUE TITLE
The card bracket?

### ISSUE THREAD

**Issue by A-Small-Mice** [hkzlab/CGA_Redux#1]
I need 3D printing the bracket data for the card..

**Comment by hkzlab** [comment]
I did not design the bracket. Have a look at the following links for the measurements.

https://www.mouser.it/ProductDetail/Keystone-Electronics/9200-1?qs=mj8EgzjLv%252BAk5a7ALZYoog%3D%3D&countrycode=DE&currencycode=EUR
https://www.mouser.it/datasheet/2/215/200-1-741899.pdf

I drilled the hole for the composite connector myself. You'll have to obtain precise measurements for that using either a gerber viewer or from inside kicad by opening the pcb files.
